# Generated by Django 5.1.6 on 2025-02-19 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('varieta', models.CharField(max_length=100)),
                ('posizione', models.TextField()),
                ('coordinate_catastali', models.CharField(blank=True, max_length=255, null=True)),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MezzoAgricolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modello', models.CharField(max_length=100)),
                ('targa', models.CharField(max_length=50, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('ruolo', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdottoFitosanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('principio_attivo', models.CharField(max_length=100)),
                ('tempo_carenza', models.IntegerField(help_text='Tempo di carenza in giorni')),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('potatura', 'Potatura'), ('concimazione', 'Concimazione'), ('irrigazione', 'Irrigazione'), ('raccolta', 'Raccolta'), ('trattamento', 'Trattamento fitosanitario')], max_length=50)),
                ('descrizione', models.TextField()),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quaderno.campo')),
                ('mezzo_agricolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quaderno.mezzoagricolo')),
                ('personale', models.ManyToManyField(blank=True, to='quaderno.personale')),
            ],
        ),
        migrations.CreateModel(
            name='Trattamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField(help_text='Dose in litri/ettaro')),
                ('data', models.DateField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quaderno.campo')),
                ('operatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quaderno.prodottofitosanitario')),
            ],
        ),
    ]
