# Generated by Django 5.1.6 on 2025-02-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='status',
            field=models.CharField(choices=[('todo', 'DeFacut'), ('pending', 'InExecutie'), ('done', 'Executat'), ('delayed', 'Probleme')], default='todo', max_length=10),
        ),
    ]
