# Generated by Django 5.1.6 on 2025-02-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0004_alter_attivita_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attivita',
            options={'verbose_name_plural': 'Attivita'},
        ),
        migrations.AlterModelOptions(
            name='campo',
            options={'verbose_name_plural': 'Campi'},
        ),
        migrations.AlterModelOptions(
            name='mezzoagricolo',
            options={'verbose_name_plural': 'Mezzi agricoli'},
        ),
        migrations.AlterModelOptions(
            name='personale',
            options={'verbose_name_plural': 'Personale'},
        ),
        migrations.AlterModelOptions(
            name='prodottofitosanitario',
            options={'verbose_name_plural': 'Prodotti fitosanitari'},
        ),
        migrations.AlterModelOptions(
            name='trattamento',
            options={'verbose_name_plural': 'Trattamenti'},
        ),
    ]
