# Generated by Django 5.1.6 on 2025-02-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0005_alter_attivita_options_alter_campo_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personale',
            new_name='Operatore',
        ),
        migrations.AlterModelOptions(
            name='operatore',
            options={'verbose_name_plural': 'Operatori'},
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='personale',
        ),
        migrations.AddField(
            model_name='attivita',
            name='operatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quaderno.operatore'),
        ),
    ]
