# Generated by Django 5.1.6 on 2025-02-20 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0006_rename_personale_operatore_alter_operatore_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trattamento',
            name='responsabile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trattamento',
            name='status',
            field=models.CharField(choices=[('todo', 'DeFacut'), ('pending', 'InExecutie'), ('done', 'Executat'), ('delayed', 'Probleme')], default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='operatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quaderno.operatore'),
        ),
    ]
