# Generated by Django 5.1.6 on 2025-02-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0007_trattamento_responsabile_trattamento_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('descrizione', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Operazioni',
            },
        ),
        migrations.RemoveField(
            model_name='attivita',
            name='tipo',
        ),
        migrations.AddField(
            model_name='attivita',
            name='operazione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quaderno.operazione'),
        ),
    ]
