# Generated by Django 5.1.6 on 2025-02-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0008_operazione_remove_attivita_tipo_attivita_operazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operazione',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
