# Generated by Django 5.1.6 on 2025-02-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0009_alter_operazione_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attivita',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
