# Generated by Django 5.1.6 on 2025-02-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0010_alter_attivita_descrizione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attivita',
            options={'verbose_name_plural': 'Activitati'},
        ),
        migrations.AlterModelOptions(
            name='campo',
            options={'verbose_name_plural': 'Parcele'},
        ),
        migrations.AlterModelOptions(
            name='mezzoagricolo',
            options={'verbose_name_plural': 'Mijloace agricole'},
        ),
        migrations.AlterModelOptions(
            name='operazione',
            options={'verbose_name_plural': 'Operatii'},
        ),
        migrations.AlterModelOptions(
            name='prodottofitosanitario',
            options={'verbose_name_plural': 'Produse fitosanitare'},
        ),
        migrations.AlterModelOptions(
            name='trattamento',
            options={'verbose_name_plural': 'Tratamente'},
        ),
        migrations.AddField(
            model_name='trattamento',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
