# Generated by Django 5.1.6 on 2025-02-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quaderno', '0011_alter_attivita_options_alter_campo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operazione',
            options={'verbose_name_plural': 'Lucrari'},
        ),
    ]
